name: Basic commit Pipeline

on:
  push:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore Dependencies
        run: dotnet restore
      - name: Build Project
        run: dotnet build --no-restore
      - name: Run Unit Tests
        run: dotnet test --filter 'FullyQualifiedName!~OurNotesAppBackEnd.Tests.Integration' --no-build --verbosity normal
